### ISSUE TITLE
HTTPS backend not available

### ISSUE THREAD

**Issue by zdevi** [terraform-google-modules/terraform-google-lb-http#34] opened 2018-10-08 14:48 UTC
I'm trying to setup HTTPS backend configuration with :

`  backend_protocol  = "HTTPS"`

But i got this error :
* google_compute_backend_service.default: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.healthChecks[0]': 'https://www.googleapis.com/compute/v1/projects/setjemesian-terraform-admin/global/httpHealthChecks/web-lb-backend-0'. This HTTPS/HTTP2 backend service supports HealthCheck and HttpsHealthCheck, invalid

The module works when i don't specify backend_protocol, but with the default value (HTTP)
Am I doing it the wrong way ?

**Comment by jeremywadsack** [comment] 2018-10-11 22:53
It appears that the problem is that is [only sets up `google_compute_http_health_check` resources](https://github.com/GoogleCloudPlatform/terraform-google-lb-http/blob/e54571141bd82dce2883b16d5a00efe6069d0e5a/main.tf#L92), when it should be creating `google_compute_https_health_check` resources when `backend_protocol = "HTTPS"`.

I think this could be addressed by using a `count` [similar to how `google_compute_target_http_proxy` or `google_compute_target_https_proxy` is created based on `var.ssl`](https://github.com/GoogleCloudPlatform/terraform-google-lb-http/blob/e54571141bd82dce2883b16d5a00efe6069d0e5a/main.tf#L54):

```
resource "google_compute_http_health_check" "default" {
  ...
  count        = "${var.backend_protocol ==  "HTTPS" ? 0 : length(var.backend_params)}"
}

resource "google_compute_https_health_check" "default" {
  ...
  count        = "${var.backend_protocol ==  "HTTPS" ? length(var.backend_params) : 0}"
}
```

Then something to choose whichever is the appropriate proxy?

```
resource "google_compute_backend_service" "default" {
  ...
  health_checks   = ["${coalesce(element(google_compute_http_health_check.default.*.self_link, count.index), element(google_compute_https_health_check.default.*.self_link, count.index)}"]
  ...
}
```

**Closed** 2019-12-16 15:46 UTC
Labels: enhancement, triaged
